import { useEffect, useRef, useState } from "react";

type Ability = "nova" | "blink" | "shield" | "overdrive";
type Mode = "menu" | "play" | "upgrade" | "pause" | "settings" | "controls" | "end";
type Quality = "low" | "medium" | "high";
type Player = { x:number;y:number;hp:number;maxHp:number;speed:number;fire:number;fireRate:number;dashCd:number;dashCooldown:number;abilityCd:number;abilityRate:number;ability:Ability;abilityActive:number;color:string;dead:boolean;level:number;xp:number;nextXp:number;damage:number;shots:number;crit:number;critMult:number;armor:number;regen:number;lifesteal:number;bossBonus:number;abilityPower:number;creditBonus:number;score:number };
type Enemy = { x:number;y:number;r:number;hp:number;maxHp:number;speed:number;damage:number;kind:"husk"|"shooter"|"charger"|"splitter"|"boss";elite:boolean;phase:number };
type Bullet = { x:number;y:number;vx:number;vy:number;damage:number;life:number;enemy:boolean;r:number;owner:number };
type ControlKeys = { p1up:string;p1down:string;p1left:string;p1right:string;p1dash:string;p1ability:string;p2up:string;p2down:string;p2left:string;p2right:string;p2dash:string;p2ability:string };
type Settings = { quality:Quality;shake:boolean;particles:boolean;fps:boolean;zoom:number;difficulty:"normal"|"hard";keys:ControlKeys };
const W=1200,H=675,MAX_WAVE=40;
const defaults:Settings={quality:"high",shake:true,particles:true,fps:false,zoom:1,difficulty:"normal",keys:{p1up:"KeyW",p1down:"KeyS",p1left:"KeyA",p1right:"KeyD",p1dash:"Space",p1ability:"KeyE",p2up:"ArrowUp",p2down:"ArrowDown",p2left:"ArrowLeft",p2right:"ArrowRight",p2dash:"ShiftRight",p2ability:"Numpad0"}};
const upgrades=[
 ["🔥 OVERCHARGE","Damage +18%","damage"],["💨 LIGHT FEET","Speed +10%","speed"],["⚡ QUICK HANDS","Fire cooldown -14%","fire"],["❤️ TITAN CORE","Max HP +30 + heal","hp"],["🛡 ARMOR PLATE","Damage taken -10%","armor"],["🎯 CRITICAL","Crit chance +8%","crit"],["🩸 VAMPIRIC","Heal 3% of damage","lifesteal"],["💚 REGEN","+1.5 HP/sec","regen"],["🔫 TWIN BARREL","+1 projectile","shots"],["☄ HEAVY ROUNDS","Damage +25%","damage"],["🏃 AFTERBURN","Dash cooldown -18%","dash"],["✨ ABILITY CORE","Ability cooldown -20%","ability"],["💰 BOUNTY DRIVE","Credits earned +20%","credits"],["💥 OVERKILL","Crit damage +35%","critDamage"],["👑 BOSS HUNTER","Boss damage +20%","boss"],["🔥 EMBER FUEL","Ability power +25%","abilityPower"] as const];
const abilities:Record<Ability,{name:string;desc:string;cd:number}>= {nova:{name:"NOVA",desc:"Blast everything nearby",cd:12},blink:{name:"BLINK",desc:"Teleport and become invulnerable",cd:9},shield:{name:"EMBER SHIELD",desc:"Become immune for 3 seconds",cd:14},overdrive:{name:"OVERDRIVE",desc:"Move and fire much faster",cd:18}};
function loadSettings():Settings{try{return {...defaults,...JSON.parse(localStorage.getItem("emberfall.settings.v2")||"{}")}}catch{return defaults}}
function saveSettings(x:Settings){try{localStorage.setItem("emberfall.settings.v2",JSON.stringify(x))}catch{}}
function fmtKey(k:string){return k.replace("Key","").replace("Arrow","↑").replace("Right","").replace("Left","").replace("Numpad0","NUM 0").replace("Space","SPACE")}
export default function Game(){
 const canvasRef=useRef<HTMLCanvasElement>(null),keys=useRef<Record<string,boolean>>({}),last=useRef(0),raf=useRef(0),renderClock=useRef(0),settingsRef=useRef(loadSettings());
 const [,tick]=useState(0);const[screen,setScreen]=useState<Mode>("menu");const[settings,setSettings]=useState(settingsRef.current);const[rebind,setRebind]=useState<string|null>(null);
 const s=useRef({players:[] as Player[],enemies:[] as Enemy[],bullets:[] as Bullet[],wave:0,time:0,spawn:0,kills:0,credits:0,shake:0,message:"",victory:false,bossSpawned:false,upgradeChoices:[] as (readonly string[])[],particles:[] as Array<{x:number,y:number,vx:number,vy:number,life:number,size:number}>,fps:0,frames:0,fpsTime:0}).current;
 const updateSettings=(patch:Partial<Settings>)=>{const n={...settings,...patch};settingsRef.current=n;setSettings(n);saveSettings(n)};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(rebind){const n={...settingsRef.current,keys:{...settingsRef.current.keys,[rebind]:e.code}};settingsRef.current=n;setSettings(n);saveSettings(n);setRebind(null);e.preventDefault();return}keys.current[e.code]=true;if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="Escape")setScreen(x=>x==="play"?"pause":x==="pause"?"play":x)};const up=(e:KeyboardEvent)=>keys.current[e.code]=false;addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[rebind]);
 const begin=(count:1|2)=>{const make=(i:number):Player=>({x:W/2+(i?75:-75),y:H-100,hp:100,maxHp:100,speed:215,fire:0,fireRate:1,dashCd:0,dashCooldown:.9,abilityCd:0,abilityRate:1,ability:i?"shield":"nova",abilityActive:0,color:i?"#65e6ff":"#ff9f43",dead:false,level:1,xp:0,nextXp:30,damage:1,shots:1,crit:.05,critMult:2.5,armor:0,regen:0,lifesteal:0,bossBonus:1,abilityPower:1,creditBonus:1,score:0});s.players=Array.from({length:count},(_,i)=>make(i));s.enemies=[];s.bullets=[];s.particles=[];s.wave=0;s.time=0;s.spawn=0;s.kills=0;s.credits=0;s.shake=0;s.victory=false;s.bossSpawned=false;s.upgradeChoices=[];nextWave()};
 const nextWave=()=>{s.wave++;s.time=0;s.spawn=0;s.enemies=[];s.bullets=[];s.bossSpawned=false;s.upgradeChoices=[];if(s.wave>MAX_WAVE){s.victory=true;setScreen("end");return}s.message=s.wave%5===0?"⚠ BOSS WAVE":"WAVE "+s.wave;setScreen("play");tick(v=>v+1)};
 const rollUpgrades=()=>{s.upgradeChoices=[...upgrades].sort(()=>Math.random()-.5).slice(0,4)};
 const apply=(kind:string)=>{for(const p of s.players){if(kind==="damage")p.damage*=1.18;if(kind==="speed")p.speed*=1.10;if(kind==="fire")p.fireRate=Math.max(.35,p.fireRate*.86);if(kind==="hp"){p.maxHp+=30;p.hp=p.maxHp}if(kind==="armor")p.armor=Math.min(.65,p.armor+.10);if(kind==="crit")p.crit=Math.min(.75,p.crit+.08);if(kind==="lifesteal")p.lifesteal=Math.min(.20,p.lifesteal+.03);if(kind==="regen")p.regen+=1.5;if(kind==="shots")p.shots=Math.min(5,p.shots+1);if(kind==="dash")p.dashCooldown=Math.max(.35,p.dashCooldown*.82);if(kind==="ability")p.abilityRate=Math.max(.4,p.abilityRate*.80);if(kind==="credits")p.creditBonus=Math.min(3,p.creditBonus+.20);if(kind==="critDamage")p.critMult=Math.min(5,p.critMult+.35);if(kind==="boss")p.bossBonus=Math.min(3,p.bossBonus+.20);if(kind==="abilityPower")p.abilityPower=Math.min(3,p.abilityPower*1.25)}nextWave()};
 const useAbility=(p:Player)=>{if(p.abilityCd>0||p.dead)return;const a=p.ability;if(a==="nova"){for(let i=s.enemies.length-1;i>=0;i--){const e=s.enemies[i];if(Math.hypot(e.x-p.x,e.y-p.y)<250){const hit=230*p.damage*p.abilityPower*(e.kind==="boss"?p.bossBonus:1);e.hp-=hit;if(e.hp<=0){s.enemies.splice(i,1);s.kills++;s.credits+=Math.ceil((e.kind==="boss"?120:e.elite?10:8)*p.creditBonus)}}}s.shake=12}else if(a==="blink"){const k=keys.current,q=settingsRef.current.keys,pi=s.players.indexOf(p),pref=pi===1?{up:q.p2up,down:q.p2down,left:q.p2left,right:q.p2right}:{up:q.p1up,down:q.p1down,left:q.p1left,right:q.p1right},dx=Number(!!k[pref.right])-Number(!!k[pref.left]),dy=Number(!!k[pref.down])-Number(!!k[pref.up]),l=Math.hypot(dx,dy)||1,range=230*p.abilityPower;p.x=Math.max(25,Math.min(W-25,p.x+dx/l*range));p.y=Math.max(25,Math.min(H-25,p.y+dy/l*range));p.abilityActive=.55}else if(a==="shield"){p.abilityActive=3*p.abilityPower}else{p.abilityActive=5*p.abilityPower}p.abilityCd=abilities[a].cd*p.abilityRate};
 const spawn=()=>{const w=s.wave,a=Math.random()*Math.PI*2,r=520,boss=w%5===0&&!s.bossSpawned,roll=Math.random();if(boss)s.bossSpawned=true;let kind:Enemy["kind"]=boss?"boss":w>=12&&roll<.10?"splitter":w>=8&&roll<.22?"charger":roll<.38?"shooter":"husk";const scale=1+(w-1)*.075*(settingsRef.current.difficulty==="hard"?1.18:1);const hp=(kind==="boss"?900+w*230:kind==="splitter"?70+w*8:kind==="charger"?55+w*9:kind==="shooter"?42+w*7:28+w*6)*scale;s.enemies.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,r:kind==="boss"?46:kind==="splitter"?22:kind==="charger"?20:16,hp,maxHp:hp,speed:kind==="boss"?38+w:kind==="splitter"?65+w:kind==="charger"?120+w*2:kind==="shooter"?58+w:76+w*1.6,damage:kind==="boss"?24+w:7+w*.85,kind,elite:kind!=="boss"&&w>=6&&Math.random()<Math.min(.28,w*.012),phase:0})};
 const burst=(x:number,y:number)=>{if(!settingsRef.current.particles)return;const amount=settingsRef.current.quality==="high"?10:settingsRef.current.quality==="medium"?5:2;for(let i=0;i<amount;i++){const a=Math.random()*Math.PI*2;s.particles.push({x,y,vx:Math.cos(a)*(30+Math.random()*80),vy:Math.sin(a)*(30+Math.random()*80),life:.35+Math.random()*.5,size:2+Math.random()*3})}};
 const update=(dt:number)=>{s.time+=dt;s.spawn-=dt;s.shake=Math.max(0,s.shake-dt*25);const w=s.wave;const cap=Math.min(75,7+Math.floor(w*1.8)),waveDuration=Math.min(42,14+w*1.1);if(s.spawn<=0&&s.enemies.length<cap&&s.time<waveDuration){spawn();s.spawn=Math.max(.13,.82-w*.013)}
 s.players.forEach((p,i)=>{if(p.dead)return;const k=keys.current,q=settingsRef.current.keys,pref=i?{up:q.p2up,down:q.p2down,left:q.p2left,right:q.p2right,dash:q.p2dash,ability:q.p2ability}:{up:q.p1up,down:q.p1down,left:q.p1left,right:q.p1right,dash:q.p1dash,ability:q.p1ability};let dx=Number(!!k[pref.right])-Number(!!k[pref.left]),dy=Number(!!k[pref.down])-Number(!!k[pref.up]),l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;if(k[pref.dash]&&p.dashCd<=0){p.dashCd=p.dashCooldown;p.x=Math.max(25,Math.min(W-25,p.x+dx*p.speed*3.6*.18));p.y=Math.max(25,Math.min(H-25,p.y+dy*p.speed*3.6*.18));}p.dashCd=Math.max(0,p.dashCd-dt);p.abilityCd=Math.max(0,p.abilityCd-dt);p.abilityActive=Math.max(0,p.abilityActive-dt);p.hp=Math.min(p.maxHp,p.hp+p.regen*dt);if(k[pref.ability])useAbility(p);const speed=p.speed*(p.abilityActive>0&&p.ability==="overdrive"?1.45:1);p.x=Math.max(22,Math.min(W-22,p.x+dx*speed*dt));p.y=Math.max(22,Math.min(H-22,p.y+dy*speed*dt));p.fire=Math.max(0,p.fire-dt);let target:Enemy|undefined,best=Infinity;for(const e of s.enemies){const d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<best){best=d;target=e}}if(target&&p.fire<=0){const a=Math.atan2(target.y-p.y,target.x-p.x);for(let n=0;n<p.shots;n++){const spread=(n-(p.shots-1)/2)*.10;let dmg=15*p.damage;if(Math.random()<p.crit)dmg*=p.critMult;s.bullets.push({x:p.x,y:p.y,vx:Math.cos(a+spread)*570,vy:Math.sin(a+spread)*570,damage:dmg,life:1.7,enemy:false,r:4,owner:i})}p.fire=Math.max(.045,.25*p.fireRate-(p.abilityActive>0&&p.ability==="overdrive"?.10:0))}});
 for(let i=s.bullets.length-1;i>=0;i--){const b=s.bullets[i];b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.life<=0||b.x<-50||b.x>W+50||b.y<-50||b.y>H+50){s.bullets.splice(i,1);continue}if(b.enemy){let hit=false;for(const p of s.players)if(!p.dead&&p.abilityActive<=0&&Math.hypot(p.x-b.x,p.y-b.y)<20){p.hp-=b.damage*(1-p.armor);hit=true;if(p.hp<=0)p.dead=true;break}if(hit)s.bullets.splice(i,1)}else{for(let ei=s.enemies.length-1;ei>=0;ei--){const e=s.enemies[ei];if(Math.hypot(e.x-b.x,e.y-b.y)<e.r+b.r){const p=s.players[b.owner],hitDamage=b.damage*(e.kind==="boss"?p.bossBonus:1);e.hp-=hitDamage;p.hp=Math.min(p.maxHp,p.hp+hitDamage*p.lifesteal);if(e.hp<=0){s.enemies.splice(ei,1);s.kills++;s.credits+=Math.ceil((e.kind==="boss"?120:e.elite?10:2+Math.ceil(w*.4))*p.creditBonus);p.score+=e.kind==="boss"?1200:e.elite?60:10;p.xp+=e.kind==="boss"?40:e.elite?12:5;burst(e.x,e.y);if(e.kind==="splitter"&&s.enemies.length<cap){for(let z=0;z<2;z++)s.enemies.push({x:e.x+(z?14:-14),y:e.y,r:10,hp:18+w*3,maxHp:18+w*3,speed:95+w,damage:5+w*.5,kind:"husk",elite:false,phase:0})}if(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.ceil(p.nextXp*1.27);rollUpgrades();setScreen("upgrade")}}s.bullets.splice(i,1);break}}}}
 for(const e of s.enemies){const alive=s.players.filter(p=>!p.dead);if(!alive.length)break;let t=alive[0],best=Infinity;for(const p of alive){const d=(p.x-e.x)**2+(p.y-e.y)**2;if(d<best){best=d;t=p}}const a=Math.atan2(t.y-e.y,t.x-e.x),dist=Math.hypot(t.x-e.x,t.y-e.y);if(e.kind==="shooter"&&dist<390){e.x-=Math.cos(a)*e.speed*dt*.45;e.y-=Math.sin(a)*e.speed*dt*.45}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}if((e.kind==="shooter"||e.kind==="boss")&&Math.random()<dt*(e.kind==="boss"?1.2+w*.02:.5)){s.bullets.push({x:e.x,y:e.y,vx:Math.cos(a)*270,vy:Math.sin(a)*270,damage:e.damage,life:3,enemy:true,r:e.kind==="boss"?8:6,owner:-1})}for(const p of alive)if(Math.hypot(p.x-e.x,p.y-e.y)<e.r+15&&p.abilityActive<=0){p.hp-=e.damage*dt*(e.kind==="boss"?1.15:1)*(1-p.armor);if(p.hp<=0)p.dead=true}}
 for(let i=s.particles.length-1;i>=0;i--){const p=s.particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0)s.particles.splice(i,1)}
 if(s.players.every(p=>p.dead)){s.victory=false;setScreen("end");return}if(s.time>=waveDuration&&s.enemies.length===0){if(w>=MAX_WAVE){s.victory=true;setScreen("end")}else{rollUpgrades();setScreen("upgrade")}}s.frames++;s.fpsTime+=dt;if(s.fpsTime>=.5){s.fps=Math.round(s.frames/s.fpsTime);s.frames=0;s.fpsTime=0}}
 const draw=()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const q=settingsRef.current;const sx=q.shake?((Math.random()-.5)*s.shake):0,sy=q.shake?((Math.random()-.5)*s.shake):0;ctx.save();ctx.translate(sx,sy);ctx.fillStyle="#070810";ctx.fillRect(-20,-20,W+40,H+40);ctx.strokeStyle="rgba(255,180,100,.055)";ctx.lineWidth=1;for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const p of s.particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle="#ffb45f";ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const b of s.bullets){ctx.fillStyle=b.enemy?"#ff4f68":"#ffd18a";if(q.quality!=="low"){ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=8}ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;for(const e of s.enemies){ctx.fillStyle=e.kind==="boss"?"#ff3d6e":e.kind==="splitter"?"#b77cff":e.kind==="shooter"?"#7fe8ff":e.kind==="charger"?"#ff8fc7":"#ff795c";ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();if(e.elite){ctx.strokeStyle="#ffe66d";ctx.lineWidth=3;ctx.stroke()}ctx.fillStyle="#222";ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2,4);ctx.fillStyle="#76ff8b";ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2*Math.max(0,e.hp/e.maxHp),4)}for(const p of s.players){if(p.dead)continue;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=q.quality==="low"?0:14;ctx.beginPath();ctx.moveTo(p.x+18,p.y);ctx.lineTo(p.x-14,p.y-13);ctx.lineTo(p.x-8,p.y);ctx.lineTo(p.x-14,p.y+13);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#222";ctx.fillRect(p.x-22,p.y+20,44,5);ctx.fillStyle="#65ff9b";ctx.fillRect(p.x-22,p.y+20,44*Math.max(0,p.hp/p.maxHp),5);if(p.abilityActive>0){ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,28,0,Math.PI*2);ctx.stroke()}}ctx.restore()};
 useEffect(()=>{if(screen!=="play")return;last.current=performance.now();renderClock.current=0;const loop=(t:number)=>{const dt=Math.min(.033,(t-last.current)/1000);last.current=t;update(dt);renderClock.current+=dt;const interval=settingsRef.current.quality==="low"?.033:settingsRef.current.quality==="medium"?.022:.016;if(renderClock.current>=interval){renderClock.current=0;draw()}raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[screen]);
 const button=(label:string,onClick:()=>void)=><button className="menu-button" onClick={onClick} style={{padding:"13px 18px",borderRadius:12,color:"white",cursor:"pointer",fontWeight:800,fontSize:15}}>{label}</button>;
 const panel={position:"absolute" as const,left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:"min(680px,92vw)",maxHeight:"90vh",overflowY:"auto" as const,background:"rgba(10,8,18,.96)",border:"1px solid rgba(255,180,100,.28)",borderRadius:24,padding:28,color:"white",textAlign:"center" as const,boxShadow:"0 25px 100px rgba(0,0,0,.65)"};
 const menu=<main className="game-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",color:"white"}}><section style={panel}><div style={{fontSize:12,letterSpacing:5,opacity:.6}}>VERSION 2.1 • ARENA SURVIVAL</div><h1 style={{fontSize:"clamp(48px,10vw,86px)",margin:"8px 0",letterSpacing:-4}}>EMBERFALL</h1><p style={{fontSize:18,opacity:.78}}>Survive. Upgrade. Become completely unreasonable.</p><div style={{display:"grid",gap:12,marginTop:24}}>{button("🔥 SOLO RUN",()=>begin(1))}{button("👥 LOCAL 2 PLAYER",()=>begin(2))}{button("⚙ SETTINGS",()=>setScreen("settings"))}</div><p style={{opacity:.5,fontSize:13,marginTop:22}}>V2.1 • fixed upgrades • fair wave pacing • remappable controls • local co-op</p></section></main>;
 if(screen==="menu")return menu;
 if(screen==="settings")return <main className="game-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",color:"white"}}><section style={panel}><h2 style={{fontSize:32,marginTop:0}}>⚙ SETTINGS</h2><p style={{opacity:.65}}>Tune Emberfall for your device.</p><div style={{display:"grid",gap:14,textAlign:"left",marginTop:20}}><label>GRAPHICS QUALITY <select value={settings.quality} onChange={e=>updateSettings({quality:e.target.value as Quality})} style={{float:"right",padding:8,borderRadius:8}}><option value="low">Low — maximum FPS</option><option value="medium">Medium — balanced</option><option value="high">High — prettier</option></select></label><label>DIFFICULTY <select value={settings.difficulty} onChange={e=>updateSettings({difficulty:e.target.value as "normal"|"hard"})} style={{float:"right",padding:8,borderRadius:8}}><option value="normal">Normal</option><option value="hard">Hard</option></select></label><label>SCREEN SHAKE <input type="checkbox" checked={settings.shake} onChange={e=>updateSettings({shake:e.target.checked})} style={{float:"right"}}/></label><label>PARTICLES <input type="checkbox" checked={settings.particles} onChange={e=>updateSettings({particles:e.target.checked})} style={{float:"right"}}/></label><label>FPS COUNTER <input type="checkbox" checked={settings.fps} onChange={e=>updateSettings({fps:e.target.checked})} style={{float:"right"}}/></label><label>UI ZOOM <input type="range" min=".85" max="1.15" step=".05" value={settings.zoom} onChange={e=>updateSettings({zoom:Number(e.target.value)})} style={{float:"right",width:180}}/></label></div><div style={{display:"flex",gap:10,justifyContent:"center",marginTop:28,flexWrap:"wrap"}}>{button("🎮 CONTROLS",()=>setScreen("controls"))}{button("↩ BACK",()=>setScreen("menu"))}</div></section></main>;
 if(screen==="controls")return <main className="game-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",color:"white"}}><section style={panel}><h2>🎮 CONTROLS</h2><p style={{opacity:.65}}>Click a key to change it. Press any new key.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,textAlign:"left"}}>{Object.entries(settings.keys).map(([name,key])=><button key={name} className="menu-button" onClick={()=>setRebind(name)} style={{padding:12,borderRadius:10,color:"white",textAlign:"left",cursor:"pointer"}}><b>{name.replace("p1","P1 ").replace("p2","P2 ").toUpperCase()}</b><span style={{float:"right",opacity:.8}}>{rebind===name?"PRESS KEY…":fmtKey(key)}</span></button>)}</div><div style={{marginTop:22}}>{button("↩ BACK",()=>setScreen("settings"))}</div></section></main>;
 if(screen==="upgrade")return <main className="game-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",color:"white"}}><section style={panel}><div style={{fontSize:12,letterSpacing:4,opacity:.6}}>LEVEL UP</div><h2 style={{fontSize:32}}>⚡ CHOOSE YOUR POWER</h2><p style={{opacity:.65}}>The arena is getting angrier. Pick something useful.</p><div style={{display:"grid",gap:10}}>{(s.upgradeChoices.length?s.upgradeChoices:upgrades.slice(0,4)).map(u=><button key={u[2]} onClick={()=>apply(u[2])} className="menu-button" style={{padding:16,textAlign:"left",color:"white",borderRadius:14,cursor:"pointer"}}><b style={{fontSize:16}}>{u[0]}</b><br/><small style={{opacity:.7}}>{u[1]}</small></button>)}</div></section></main>;
 if(screen==="pause")return <main className="game-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",color:"white"}}><canvas ref={canvasRef} width={W} height={H} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"contain"}}/><section style={{...panel,width:"min(420px,90vw)"}}><h2>⏸ PAUSED</h2>{button("▶ RESUME",()=>setScreen("play"))} <span style={{margin:5}}/>{button("⚙ SETTINGS",()=>setScreen("settings"))}<div style={{marginTop:14}}>{button("🏠 MENU",()=>setScreen("menu"))}</div></section></main>;
 if(screen==="end")return <main className="game-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",color:"white"}}><section style={panel}><div style={{fontSize:50}}>{s.victory?"🏆":"💀"}</div><h1>{s.victory?"EMBERFALL CONQUERED":"RUN OVER"}</h1><p>Wave {s.wave} • {s.kills} kills • {s.credits} credits</p>{button("🔥 PLAY AGAIN",()=>begin(1))} <span style={{margin:5}}/>{button("🏠 MENU",()=>setScreen("menu"))}</section></main>;
 return <main className="game-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",overflow:"hidden"}}><div style={{position:"relative",width:"min(100vw,calc(100vh * 1.7778))",aspectRatio:"16 / 9",maxHeight:"100vh",transform:`scale(${settings.zoom})`,transformOrigin:"center"}}><canvas ref={canvasRef} width={W} height={H} style={{width:"100%",height:"100%",display:"block",imageRendering:"auto"}}/><div style={{position:"absolute",top:10,left:12,right:12,color:"white",fontFamily:"system-ui",fontWeight:800,fontSize:13,textShadow:"0 2px 6px #000",pointerEvents:"none"}}>WAVE {s.wave}/{MAX_WAVE} • KILLS {s.kills} • CREDITS {s.credits} • {Math.max(0,Math.ceil(Math.min(42,14+s.wave*1.1)-s.time))}s • {s.message}<span style={{float:"right"}}>P1 {Math.ceil(s.players[0]?.hp||0)} HP • {s.players[0]?abilities[s.players[0].ability].name:""} {s.players[0]?.abilityCd>0?Math.ceil(s.players[0].abilityCd)+"s":"READY"}</span></div>{settings.fps&&<div style={{position:"absolute",bottom:8,left:10,color:"#8ff",fontWeight:800}}>{s.fps} FPS • {settings.quality.toUpperCase()}</div>}<button aria-label="Pause" onClick={()=>setScreen("pause")} style={{position:"absolute",top:8,right:8,opacity:.75,border:0,borderRadius:8,padding:"7px 10px",cursor:"pointer"}}>Ⅱ</button></div></main>;
}